### PR TITLE
updating sso token generation to not use mcrypt but openssl

### PR DESCRIPTION
**Pull request by nolazybits**
removing mcrypt dependency
updating README

### CODE REVIEW

**Comment by nolazybits** [comment]
anyone?

**Comment by wlrs** [comment]
@nolazybits Sorry for the delay here. This seems like a good change, let us check it out!

**Comment by Jfcurd** [comment]
@nolazybits I've tested this out locally and the generated hashes match my test cases. Gonna go ahead and merge this in. Thanks for the improvements!

**Comment by nolazybits** [comment]
Thanks for checking it out and merging it
👍

**Pull request merged**
